const todoList = [
  {
    id: 1,
    title: "Draft Project Proposal",
    description: "Outline the objectives, deliverables, and timeline for the upcoming project.",
    priority: "first",
    status: "todo",
    createdDate: "2024-12-04",
    updatedDate: "2023-12-02",
    createdTime: "10:00:00",
    updatedTime: "12:00:00",
  },
  {
    id: 2,
    title: "Design Wireframes",
    description: "Create initial wireframes for the main screens of the application to present to stakeholders.",
    priority: "second",
    status: "in-progress",
    createdDate: "2023-12-01",
    updatedDate: "2023-12-03",
    createdTime: "11:00:00",
    updatedTime: "08:30:00",
  },
  {
    id: 3,
    title: "Develop Authentication Module",
    description: "Implement user login, signup, and password recovery functionality.",
    priority: "first",
    status: "todo",
    createdDate: "2023-12-01",
    updatedDate: "2023-12-02",
    createdTime: "12:00:00",
    updatedTime: "14:00:00",
  },
  {
    id: 4,
    title: "Fix Dashboard Bugs",
    description: "Resolve layout and functionality issues in the dashboard component.",
    priority: "third",
    status: "in-progress",
    createdDate: "2023-12-01",
    updatedDate: "2023-12-04",
    createdTime: "13:00:00",
    updatedTime: "09:00:00",
  },
  {
    id: 5,
    title: "Write Unit Tests for API",
    description: "Create and run unit tests to validate the functionality of API endpoints.",
    priority: "second",
    status: "in-progress",
    createdDate: "2024-12-04",
    updatedDate: "2023-12-02",
    createdTime: "14:00:00",
    updatedTime: "16:00:00",
  },
  {
    id: 6,
    title: "Optimize Database Performance",
    description: "Analyze slow queries and optimize database indexes to improve response times.",
    priority: "first",
    status: "in-progress",
    createdDate: "2023-12-01",
    updatedDate: "2023-12-03",
    createdTime: "15:00:00",
    updatedTime: "10:00:00",
  },
  {
    id: 7,
    title: "Plan Sprint Tasks",
    description: "Organize tasks for the upcoming sprint and allocate resources effectively.",
    priority: "first",
    status: "todo",
    createdDate: "2024-12-04",
    updatedDate: "2023-12-04",
    createdTime: "16:00:00",
    updatedTime: "11:00:00",
  },
  {
    id: 8,
    title: "Code Review for Team Members",
    description: "Review code submissions from team members and provide feedback for improvement.",
    priority: "second",
    status: "done",
    createdDate: "2024-12-04",
    updatedDate: "2023-12-02",
    createdTime: "17:00:00",
    updatedTime: "18:30:00",
  },
  {
    id: 9,
    title: "Update Project Documentation",
    description: "Document recent changes to the project, including updated features and bug fixes.",
    priority: "third",
    status: "in-progress",
    createdDate: "2024-12-04",
    updatedDate: "2023-12-03",
    createdTime: "18:00:00",
    updatedTime: "19:00:00",
  },
  {
    id: 10,
    title: "Prepare Client Presentation",
    description: "Create slides showcasing the project progress and key achievements for the client meeting.",
    priority: "first",
    status: "todo",
    createdDate: "2024-12-04",
    updatedDate: "2023-12-04",
    createdTime: "19:00:00",
    updatedTime: "20:00:00",
  },
];

export default todoList;